---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mta-alert
  name: mta-alert
  # namespace: mta-infra
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "8090"
spec:
  ports:
  - name: mta-alert
    port: 8080
    protocol: TCP
    targetPort: 8080
    # nodePort: 31003
  - name: nodejs-exporter
    port: 8090
    protocol: TCP
    targetPort: 8090
    # nodePort: 30003
  selector:
    app: mta-alert
    # ver: 1.0.0
  # type: NodePort
  type: ClusterIP
